version: '3'

services:
  mongo:
    image: mongo:4.0.6
    container_name: mongo
    volumes:
      - mongo_db:/data/db
    ports:
      - '27017:27017'
    logging:
      options:
        max-size: '200k'
        max-file: '10'
    restart: always

volumes:
  mongo_db:
